import test from 'node:test';import assert from 'node:assert/strict';
import {generate,seededRandom,countSolutions,validBoard,TIERS} from '../sudoku/solver.mjs';
import {createState,edit,undo,hint,conflicts,complete,tick,validateSaved,load,save} from '../sudoku/state.mjs';
const puzzle=generate('easy',seededRandom(42));
test('unique puzzles across seeds and tiers with meaningful clues',()=>{const seen=new Set();for(const tier of Object.keys(TIERS))for(let seed=1;seed<=5;seed++){const p=generate(tier,seededRandom(seed));assert.equal(validBoard(p.solution,true),true);assert.equal(countSolutions(p.givens),1);assert.ok(p.givens.filter(Boolean).length>=TIERS[tier]);assert.ok(p.givens.filter(Boolean).length<=TIERS[tier]+5);const key=p.givens.join('');assert.ok(!seen.has(key));seen.add(key);}});
test('givens immutable; notes, numbers, erase and undo are reversible',()=>{let s=createState(puzzle);const g=s.givens.findIndex(Boolean),i=s.givens.indexOf(0);assert.equal(edit(s,g,2),s);s=edit(s,i,3,true);assert.deepEqual(s.notes[i],[3]);s=edit(s,i,4,true);assert.deepEqual(undo(s).notes[i],[3]);s=edit(s,i,5);assert.equal(s.board[i],5);assert.deepEqual(s.notes[i],[]);s=edit(s,i,0);assert.equal(s.board[i],0);assert.equal(undo(s).board[i],5);});
test('conflicts are duplicates only; hint fixes erroneous full board and completion exact',()=>{let s=createState(puzzle);const i=s.givens.indexOf(0),wrong=s.solution[i]%9+1;s=edit(s,i,wrong);assert.equal(complete(s),false);s=hint(s,i);assert.equal(s.board[i],s.solution[i]);assert.equal(s.hints,1);for(let j=0;j<81;j++)if(!s.givens[j])s=edit(s,j,s.solution[j]);assert.equal(complete(s),true);s=edit(s,i,wrong);assert.equal(complete(s),false);s=hint(s);assert.equal(complete(s),true);const b=Array(81).fill(0);b[0]=b[1]=2;assert.deepEqual([...conflicts(b)],[0,1]);b[1]=0;assert.equal(conflicts(b).size,0);});
test('storage validates uniqueness, solution, givens, notes, counters and handles failures',()=>{const s=createState(puzzle);assert.ok(validateSaved(s));for(const value of [null,{}, {...s,board:[]},{...s,solution:Array(81).fill(1)},{...s,givens:Array(81).fill(0)},{...s,elapsed:-1},{...s,hints:NaN},{...s,notes:Array(81).fill([12])}])assert.equal(validateSaved(value),null);const bad=structuredClone(s);bad.board[bad.givens.findIndex(Boolean)]=0;assert.equal(validateSaved(bad),null);const storage={getItem(){throw Error();},setItem(){throw Error();}};assert.equal(load(storage),null);assert.equal(save(storage,s),false);assert.equal(load({getItem:()=>'{bad'}),null);});
test('timer excludes paused, hidden and completed time',()=>{let s=createState(puzzle);assert.equal(tick(s,1000).elapsed,1000);assert.equal(tick({...s,paused:true},1000).elapsed,0);assert.equal(tick(s,1000,true).elapsed,0);s.board=[...s.solution];assert.equal(tick(s,1000).elapsed,0);});
