const {chromium}=require('/tmp/ttt-browser/node_modules/playwright');const assert=require('node:assert/strict');
const URL=process.env.GAME_URL||'http://127.0.0.1:8765/sudoku/';
function solve(board){const b=[...board];function go(){let i=b.indexOf(0);if(i<0)return true;for(let n=1;n<=9;n++){const r=Math.floor(i/9),c=i%9;if(b.some((v,j)=>v===n&&(Math.floor(j/9)===r||j%9===c||(Math.floor(j/27)===Math.floor(r/3)&&Math.floor(j%9/3)===Math.floor(c/3)))))continue;b[i]=n;if(go())return true;b[i]=0;}return false;}assert.ok(go());return b;}
(async()=>{const browser=await chromium.launch({headless:true});try{for(const size of [{width:390,height:844},{width:360,height:640}]){
 const ctx=await browser.newContext({viewport:size,isMobile:true,hasTouch:true,deviceScaleFactor:2});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(URL);await page.waitForFunction(()=>document.querySelectorAll('.cell[data-given]').length===81).catch(async e=>{console.error(await page.locator('#status').innerText(),errors,await page.locator('#grid').innerHTML());throw e;});
 const cells=page.locator('.cell');assert.equal(await cells.count(),81);const givens=await cells.evaluateAll(a=>a.map(e=>e.dataset.given==='true'?Number(e.dataset.value):0));const solution=solve(givens),i=givens.indexOf(0);const key=n=>page.locator(`[data-digit="${n}"]`);
 const fit=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,bottom:document.querySelector('#pad').getBoundingClientRect().bottom,height:innerHeight,width:document.querySelector('.cell').getBoundingClientRect().width,target:Math.min(document.querySelector('[data-digit]').getBoundingClientRect().height,document.querySelector('[data-digit]').getBoundingClientRect().width)}));assert.equal(fit.overflow,false);assert.ok(fit.bottom<=fit.height);assert.ok(fit.width>=34);assert.ok(fit.target>=44);
 await cells.nth(i).tap();await page.locator('#pencil').tap();await key(3).tap();assert.equal(await cells.nth(i).locator('.note').count(),9);assert.match(await cells.nth(i).innerText(),/3/);await page.locator('#undo').tap();assert.equal((await cells.nth(i).innerText()).trim(),'');await key(4).tap();await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.cell[data-given]').length===81).catch(async e=>{console.error(await page.locator('#status').innerText(),errors,await page.locator('#grid').innerHTML());throw e;});assert.match(await cells.nth(i).innerText(),/4/);await cells.nth(i).tap();await page.locator('#erase').tap();await page.locator('#undo').tap();assert.match(await cells.nth(i).innerText(),/4/);await page.locator('#erase').tap();
 const peer=givens.findIndex((v,j)=>v&&Math.floor(j/9)===Math.floor(i/9));await key(givens[peer]).tap();assert.ok(await cells.nth(i).evaluate(e=>e.classList.contains('conflict')));await page.locator('#hint').tap();assert.equal(await cells.nth(i).getAttribute('data-value'),String(solution[i]));assert.match(await page.locator('#hint').innerText(),/1/);
 await page.locator('#pause').tap();assert.equal(await page.locator('#resume').isVisible(),true);const clock=await page.locator('#time').innerText();await page.waitForTimeout(1200);assert.equal(await page.locator('#time').innerText(),clock);await page.reload();await page.waitForSelector('#resume');await page.locator('#resume').tap();
 await page.locator('#new').tap();await page.locator('#confirm-cancel').tap();assert.deepEqual(await cells.evaluateAll(a=>a.map(e=>e.dataset.given==='true'?Number(e.dataset.value):0)),givens);
 await page.locator('#reset').tap();await page.locator('#confirm-ok').tap();assert.equal(await cells.nth(i).getAttribute('data-value'),'0');
 for(let j=0;j<81;j++)if(!givens[j]){await cells.nth(j).tap();await key(solution[j]).tap();}await page.waitForSelector('#victory:not([hidden])');assert.match(await page.locator('#victory').innerText(),/完成/);
 await page.locator('#victory-new').tap();await page.locator('#difficulty').selectOption('hard');await page.locator('#new').tap();await page.locator('#confirm-ok').tap();await page.waitForFunction(()=>document.querySelectorAll('.cell').length===81&&document.querySelector('#tier-label').textContent.includes('挑戰'));const next=await cells.evaluateAll(a=>a.map(e=>e.dataset.given==='true'?Number(e.dataset.value):0));assert.notDeepEqual(next,givens);solve(next);
 await page.screenshot({path:size.width===390?'/tmp/sudoku-mobile.png':'/tmp/sudoku-small.png'});assert.deepEqual(errors,[]);console.log(`${size.width}x${size.height}: touch, notes/undo, conflicts/hint, persistence/pause, confirms, full victory, hard new puzzle, fit PASS`);await ctx.close();
 } }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
