import test from 'node:test';
import assert from 'node:assert/strict';
import * as L from '../obstacle-workshop/logic.mjs';
test('each game starts a deterministic public players+1 draft, no empty demolition',()=>{
 for(const n of [2,3,4]){const ids=Array.from({length:n},(_,i)=>String(i+1)),s=L.createGame(ids,0,5,123);assert.equal(s.phase,'draft');assert.equal(s.pool.length,n+1);assert.equal(new Set(s.pool.map(c=>c.id)).size,n+1);assert.ok(s.pool.every(c=>c.type!=='demolish'&&c.owner===null));assert.deepEqual(s,L.createGame(ids,0,5,123));}
});

const msg=(s,c)=>({type:'draft',action:'claim',round:s.round,card:c});
test('exclusive claims validate exact messages, identity, stale rounds, duplicate cards and replay',()=>{let s=L.createGame(['1','2','3'],0,5,44),id=s.pool[0].id;for(const m of [null,{...msg(s,id),owner:'1'},{...msg(s,id),round:0},{...msg(s,id),action:'constructor'},msg(s,'unknown')])assert.equal(L.claim(s,'1',m),s);assert.equal(L.claim(s,'9',msg(s,id)),s);s=L.claim(s,'1',msg(s,id));assert.equal(L.claim(s,'2',msg(s,id)),s);assert.equal(L.claim(s,'1',msg(s,s.pool[1].id)),s);s=L.claim(s,'2',msg(s,s.pool[1].id));s=L.claim(s,'3',msg(s,s.pool[2].id));assert.equal(s.phase,'build');assert.equal(L.claim(s,'3',msg(s,s.pool[3].id)),s);});
test('selected type alone can build or demolish, timeout assigns once and rounds refresh',()=>{let s=L.createGame(['1','2'],0,5,1);s={...s,now:L.DRAFT};s=L.tick(s,0);assert.equal(s.phase,'build');assert.equal(new Set(Object.values(s.selections)).size,2);const chosen=L.selectedType(s,'1');assert.equal(L.place(s,'1',{type:chosen==='ice'?'fan':'ice',x:240,y:200}),s);s.pool[0].type='ice';s.pool[1].type='demolish';assert.equal(L.place(s,'2',{type:'demolish',x:250,y:210}),s);s=L.place(s,'1',{type:'ice',x:240,y:200});assert.equal(s.obstacles.length,1);s=L.place(s,'2',{type:'demolish',x:250,y:210});assert.equal(s.phase,'running');assert.equal(s.obstacles.length,0);s.obstacles=[{type:'collapse',x:240,y:200,w:80,h:20,owner:'1',collapseAt:99}];const old=s.pool;s={...s,phase:'result',phaseAt:0,now:3100};s=L.tick(s,0);assert.equal(s.phase,'draft');assert.equal(s.round,2);assert.notDeepEqual(s.pool,old);assert.equal(s.obstacles[0].collapseAt,null);assert.deepEqual(s.selections,{});assert.equal(L.createGame(['1','2']).obstacles.length,0);s=L.autoassign(s);s={...s,now:s.phaseAt+L.BUILD};assert.equal(L.tick(s,0).phase,'running');});
test('disconnect releases draft card, completes remaining choices and ends single-player rooms',()=>{let s=L.createGame(['1','2','3']);s=L.claim(s,'1',msg(s,s.pool[0].id));s=L.claim(s,'2',msg(s,s.pool[1].id));s=L.disconnect(s,'2');assert.equal(s.pool[1].owner,null);assert.equal(s.selections['2'],undefined);s=L.disconnect(s,'3');assert.equal(s.phase,'ended');let n=L.createGame(['1','2','3']);n=L.claim(n,'1',msg(n,n.pool[0].id));n=L.claim(n,'2',msg(n,n.pool[1].id));n=L.disconnect(n,'3');assert.equal(n.phase,'build');n=L.place(n,'1',{type:L.selectedType(n,'1'),x:240,y:200});n=L.disconnect(n,'2');assert.equal(n.phase,'ended');});
