const {chromium}=require('/tmp/ttt-browser/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({args:['--no-sandbox']});try{
const host=await browser.newPage({viewport:{width:1366,height:768}}),guest=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];
for(const p of [host,guest])p.on('pageerror',e=>errors.push(e.message));
await host.goto(process.env.GAME_URL||'http://127.0.0.1:8765/obstacle-workshop/');await host.locator('#create').click();await host.waitForFunction(()=>document.querySelector('#share').value.includes('#room='),null,{timeout:45000});await guest.goto(await host.locator('#share').inputValue());await host.waitForFunction(()=>document.querySelector('#players').children.length===2,null,{timeout:45000});await guest.waitForFunction(()=>document.body.dataset.phase==='lobby');await host.locator('#start').click();await guest.waitForFunction(()=>document.body.dataset.phase==='build');
async function point(p,x,y){const b=await p.locator('#arena').boundingBox();await p.mouse.move(b.x+x/1200*b.width,b.y+y/440*b.height);}
await host.locator('[data-type=spike]').click();await point(host,80,365);await host.waitForFunction(()=>document.querySelector('#arena').dataset.preview==='invalid');assert.equal(await host.locator('#result').getAttribute('data-obstacles'),'0');await point(host,250,370);await host.waitForFunction(()=>document.querySelector('#arena').dataset.preview==='valid');assert.equal(await host.locator('#result').getAttribute('data-obstacles'),'0','preview does not mutate state');await host.screenshot({path:'/tmp/workshop-desktop-1366.png'});
await host.locator('[data-type=fan]').click();const before=await host.evaluate(()=>scrollY);await host.locator('#direction').selectOption('left');assert.equal(await host.evaluate(()=>scrollY),before,'direction selection does not jump');await point(host,850,210);await host.waitForFunction(()=>document.querySelector('#arena').dataset.preview==='valid');await host.mouse.click((await host.locator('#arena').boundingBox()).x+850,(await host.locator('#arena').boundingBox()).y+210);await guest.waitForFunction(()=>document.querySelector('#result').dataset.obstacles==='1');
await guest.locator('[data-type=demolish]').click();await point(guest,860,210);await guest.waitForFunction(()=>document.querySelector('#arena').dataset.preview==='valid'&&document.querySelector('#arena').dataset.previewX==='840');await guest.screenshot({path:'/tmp/workshop-desktop-1920.png'});const b=await guest.locator('#arena').boundingBox();await guest.mouse.click(b.x+860,b.y+210);for(const p of [host,guest])await p.waitForFunction(()=>document.body.dataset.phase==='running'&&document.querySelector('#result').dataset.obstacles==='0');
for(const p of [host,guest]){await p.keyboard.down('ArrowRight');await p.keyboard.down('Space');}
await host.waitForFunction(()=>document.querySelector('[data-player="1"]').textContent.includes('通關')&&document.querySelector('[data-player="2"]').textContent.includes('通關'),null,{timeout:12000});for(const p of [host,guest]){await p.keyboard.up('ArrowRight');await p.keyboard.up('Space');await p.waitForFunction(()=>document.body.dataset.phase==='result');assert.match(await p.locator('#players').innerText(),/P1[^\n]*3 分/);assert.match(await p.locator('#players').innerText(),/P2[^\n]*3 分/);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
await host.screenshot({path:'/tmp/workshop-desktop-finish.png'});assert.deepEqual(errors,[]);console.log('PASS public PeerJS two desktop pages; invalid/valid immutable preview, direction no-jump, demolition anchor preview, keyboard finishes, synced phase/scores, 1366/1920 screenshots, zero page errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
