import {createGame,claim,selectedType,place,input,tick,disconnect,platformX,sawX,fanArea,bases,pits,DRAFT,BUILD,RUN} from './logic.mjs';
const $=id=>document.getElementById(id),colors=['#ffd16c','#66e3df','#c3a0ff','#ff91a5'];let peer,host=false,self='1',state=null,roster=[],phase='idle',seq=0,revision=0,seen=-1,generation=0,deadline,type='spike',lastFrame=performance.now(),paintState=null,roomRounds=5;const connections=new Map(),held={left:false,right:false,jump:false};
function send(c,m){if(c?.open)try{c.send(JSON.stringify(m));}catch{c.close();}}
function render(){renderDraft();const previousPhase=document.body.dataset.phase;phase=state?.phase??phase;if(phase==='running'&&previousPhase!==phase)$('arena').focus({preventScroll:true});if(phase!=='build')$('preview-status').textContent=phase==='draft'?'先搶選公共卡 · 逾時自動分配':phase==='running'?'方向鍵移動 · 點按小跳，按住跳高':'滑鼠選機關，點賽道建造 · 每人一次';document.body.dataset.phase=phase;document.body.dataset.round=state?.round??0;document.body.dataset.totalRounds=roomRounds;$('rounds').disabled=!['idle','stopped'].includes(phase);$('rounds').value=String(roomRounds);$('room-settings').textContent=roster.length?`本房間 ${roomRounds} 回合決勝`: '建立前選擇回合數（5–20）';$('start').disabled=!host||!['lobby','ended'].includes(phase)||roster.length<2;$('leave').disabled=['idle','stopped'].includes(phase);$('players').replaceChildren(...roster.map(id=>{const p=state?.players.find(p=>p.id===id),el=document.createElement('li');el.style.setProperty('--color',colors[Number(id)-1]);el.dataset.x=p?.x??0;el.dataset.y=p?.y??0;el.dataset.grounded=p?.grounded??false;el.dataset.player=id;el.textContent=`P${id}${id===self?'（你）':''} · ${state?.scores[id]??0} 分${phase==='draft'?(state.selections[id]?' ✓ 已選':' · 待選'):phase==='build'?(state.placed.includes(id)?' ✓ 已放':' · 待放'):p?.finished?' ✓ 通關':p&&!p.alive?' · 淘汰':''}`;return el;}));$('result').textContent=({idle:'尚未連線',connecting:'連線中…',lobby:`等朋友加入 · ${roster.length}/4`,draft:'同時選一張公共卡 · 先到先得',build:'只能使用已選機關 · 每人一次',running:'往右跑！綠色旗幟是終點',result:'本回合結束 · 3 秒後繼續',ended:'總分結算 · 房主可重賽',stopped:'房間已停止'})[phase];$('clock').textContent=state?`第 ${state.round}/${state.totalRounds} 回合 · ${Math.max(0,Math.ceil(((phase==='draft'?DRAFT:phase==='build'?BUILD:RUN)-(state.now-state.phaseAt))/1000))} 秒`:'';$('phase-banner').textContent=({idle:'等待工友加入',connecting:'接通工廠中…',lobby:'工友集合 · 房主開始',draft:'搶選機關 · 每人一張',build:'建造時間 · 使用已選機關',running:'開跑！前往終點',result:'回合完成 · 準備下一班',ended:'本班結算 · 房主可重賽',stopped:'工廠已休息'})[phase];$('result').dataset.obstacles=state?.obstacles.length??0;for(const el of document.querySelectorAll('[data-action]'))el.disabled=phase!=='running';}

const toolNames={spike:'尖刺',spring:'彈簧',platform:'移動平台',conveyor:'輸送帶',ice:'冰面',collapse:'崩塌平台',saw:'往復鋸片',fan:'風扇',demolish:'拆除'};let poolSignature='';
function renderDraft(){
 const current=state?.phase??phase;const chosen=selectedType(state,self);if(chosen)type=chosen;
 $('chosen-tool').textContent=chosen?`本回合已選：${toolNames[chosen]}`:current==='draft'?'同時搶選一張 · 15 秒後自動分配':'等待本回合抽卡';
 $('direction-label').hidden=current!=='build'||!['conveyor','fan'].includes(chosen);
 $('direction').querySelector('[value=up]').disabled=chosen!=='fan';if(chosen==='conveyor'&&$('direction').value==='up')$('direction').value='right';
 const signature=JSON.stringify([state?.pool,current,self,state?.placed]);if(signature===poolSignature)return;poolSignature=signature;
 const cards=document.querySelector('.tool-cards');cards.replaceChildren();
 for(const card of state?.pool??[]){const el=document.createElement('button');el.dataset.type=card.type;el.dataset.card=card.id;el.dataset.owner=card.owner??'';el.setAttribute('aria-pressed',String(card.owner===self));el.disabled=current!=='draft'||!!card.owner||!!state.selections[self];
 const icon=document.createElement('canvas');icon.width=80;icon.height=40;icon.className='tool-art';icon.setAttribute('aria-hidden','true');mechanism(icon.getContext('2d'),{type:card.type,x:0,y:10,w:['platform','conveyor','ice','collapse'].includes(card.type)?80:40,h:20,owner:card.owner??'1',direction:'right'});
 const name=document.createElement('b');name.textContent=toolNames[card.type];const owner=document.createElement('small');owner.textContent=card.owner?`P${card.owner}${card.owner===self?'（你）':''} 已選`:'可搶選';el.append(icon,name,owner);
 el.onclick=()=>{if((state?.phase??phase)!=='draft')return;const m={type:'draft',action:'claim',round:state.round,card:card.id};if(host){state=claim(state,self,m);publish();}else send(connections.get('host')?.conn,m);};cards.append(el);}
}
function publish(){revision++;for(const [id,r]of connections)if(r.ready)send(r.conn,{type:'state',self:id,revision,state,roster,phase,totalRounds:roomRounds});render();}
function cleanup(){generation++;clearTimeout(deadline);for(const r of connections.values()){clearTimeout(r.timer);r.conn.close();}connections.clear();peer?.destroy();peer=null;for(const a in held)held[a]=false;}
function stop(msg){cleanup();state=null;phase='stopped';$('status').textContent=msg;$('share-panel').hidden=true;render();}
function remove(id){const r=connections.get(id);if(!r)return;connections.delete(id);clearTimeout(r.timer);r.conn.close();roster=roster.filter(i=>i!==id);state=disconnect(state,id);publish();}
function decode(raw){if(typeof raw!=='string'||raw.length>24000)return null;try{return JSON.parse(raw);}catch{return null;}}
function wire(c,id,token){const r={conn:c,ready:false,last:Date.now(),window:Date.now(),count:0};connections.set(id,r);r.timer=setTimeout(()=>{if(token===generation){if(host)remove(id);else stop('連線逾時，請換網路或索取新連結。');}},15000);c.on('open',()=>{if(token===generation&&!host)send(c,{type:'hello'});});c.on('data',raw=>{if(token!==generation)return;const m=decode(raw);if(!m)return;const now=Date.now();if(now-r.window>1000){r.window=now;r.count=0;}if(++r.count>70){if(host)remove(id);else stop('房主傳送過快。');return;}if(m.type==='ping'){r.last=now;send(c,{type:'pong'});return;}if(m.type==='pong'){r.last=now;return;}if(host){if(!r.ready){if(m.type!=='hello'||Object.keys(m).length!==1)return;if(!['lobby','ended'].includes(phase)){send(c,{type:'closed',reason:'對局已開始'});remove(id);return;}clearTimeout(r.timer);r.ready=true;roster.push(id);r.last=now;publish();return;}if(m.type==='leave'){remove(id);return;}if(m.type==='draft'){state=claim(state,id,m);r.last=now;publish();}if(m.type==='input'){state=input(state,id,m);r.last=now;}if(m.type==='place'&&['kind,round,type,x,y','direction,kind,round,type,x,y'].includes(Object.keys(m).sort().join(','))&&m.round===state?.round){state=place(state,id,{type:m.kind,x:m.x,y:m.y,...('direction' in m?{direction:m.direction}:{})});r.last=now;publish();}}else{if(m.type==='closed'){stop(m.reason||'房主已離線');return;}if(m.type!=='state'||!Number.isSafeInteger(m.revision)||!Array.isArray(m.roster)||m.roster.length>4||!m.roster.includes(m.self)||!m.roster.every(i=>['1','2','3','4'].includes(i)))return;if(!Number.isInteger(m.totalRounds)||m.totalRounds<5||m.totalRounds>20||(m.state&&m.state.totalRounds!==m.totalRounds))return;if(m.revision<=seen)return;roomRounds=m.totalRounds;seen=m.revision;clearTimeout(r.timer);clearTimeout(deadline);r.ready=true;r.last=now;if(state?.round!==m.state?.round){seq=0;for(const a in held)held[a]=false;}state=m.state;roster=m.roster;self=m.self;phase=m.phase;$('status').textContent='已連線 · 房主負責模擬；保持頁面在前景。';render();}});c.on('close',()=>{if(token===generation){if(host)remove(id);else stop('房主已離線，房間停止。');}});c.on('error',()=>{if(token===generation){if(host)remove(id);else stop('WebRTC 失敗，請換網路。');}});}
function start(room){cleanup();const token=generation;host=!room;self=host?'1':'';state=null;roster=host?['1']:[];phase='connecting';seq=0;revision=0;seen=-1;$('share-panel').hidden=true;$('status').textContent='連線公共訊號服務…';render();const id=host?'ow-'+Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join(''):undefined;deadline=setTimeout(()=>{if(token===generation)stop('訊號服務逾時，請稍後再試。');},30000);try{peer=new Peer(id,{debug:0});}catch{stop('連線元件無法啟動');return;}peer.on('open',()=>{if(token!==generation)return;if(host){clearTimeout(deadline);phase='lobby';const u=new URL(location.href);u.hash=new URLSearchParams({room:id}).toString();$('share').value=u.href;$('share-panel').hidden=false;$('status').textContent='邀請 1–3 位朋友加入。';render();}else wire(peer.connect(room,{reliable:true,serialization:'raw',label:'workshop-v1'}),'host',token);});peer.on('connection',c=>{const slot=['2','3','4'].find(i=>!connections.has(i));if(token!==generation||!host||!slot||!['lobby','ended'].includes(phase)||c.label!=='workshop-v1'||c.serialization!=='raw'){const timer=setTimeout(()=>c.close(),5000);c.on('open',()=>{clearTimeout(timer);send(c,{type:'closed',reason:!slot?'房間已滿（最多 4 人）':'對局已開始，請等重賽。'});setTimeout(()=>c.close(),300);});return;}wire(c,slot,token);});peer.on('error',()=>{if(token===generation)stop('找不到房間或公共訊號服務失敗，請換網路。');});peer.on('disconnected',()=>{if(token===generation)stop('訊號服務已斷線，房間停止。');});}
function act(action,pressed){held[action]=pressed;if(phase!=='running')return;const m={type:'input',round:state.round,seq:++seq,action,pressed};if(host)state=input(state,self,m);else send(connections.get('host')?.conn,m);}
$('create').onclick=()=>{const selected=Number($('rounds').value);if(!Number.isInteger(selected)||selected<5||selected>20){$('status').textContent='回合數必須介於 5–20';return;}roomRounds=selected;history.replaceState(null,'',location.pathname);start(null);};$('start').onclick=()=>{if(host&&roster.length>=2&&['lobby','ended'].includes(phase)){state=createGame(roster,0,roomRounds,crypto.getRandomValues(new Uint32Array(1))[0]);seq=0;publish();}};$('leave').onclick=()=>{for(const r of connections.values())send(r.conn,host?{type:'closed',reason:'房主離開，房間停止。'}:{type:'leave'});stop('你已離開房間。');};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('share').value);}catch{$('share').select();}};
const canvas=$('arena'),ctx=canvas.getContext('2d');canvas.onclick=e=>{canvas.focus({preventScroll:true});if(phase!=='build')return;const b=canvas.getBoundingClientRect(),rawX=Math.floor((e.clientX-b.left)/b.width*1200),rawY=Math.floor((e.clientY-b.top)/b.height*440),x=type==='demolish'?rawX:Math.floor(rawX/40)*40,y=type==='demolish'?rawY:Math.floor(rawY/20)*20,dir=['conveyor','fan'].includes(type)?{direction:$('direction').value}:{},m={type:'place',round:state.round,kind:type,x,y,...dir};if(host){const next=place(state,self,{type,x,y,...dir});$('status').textContent=next===state?'無法操作：請避開安全區、重疊與固定地形；拆除須點機關。':'操作成功';state=next;publish();}else send(connections.get('host')?.conn,m);};
const keys={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'jump',a:'left',d:'right',w:'jump',' ':'jump'};window.addEventListener('keydown',e=>{if(e.target.matches('input,select')||phase!=='running')return;const a=keys[e.key]??keys[e.key.toLowerCase()];if(a){e.preventDefault();if(!e.repeat)act(a,true);}});window.addEventListener('keyup',e=>{const a=keys[e.key]??keys[e.key.toLowerCase()];if(a)act(a,false);});for(const el of document.querySelectorAll('[data-action]')){el.onpointerdown=e=>{e.preventDefault();try{el.setPointerCapture(e.pointerId);}catch{}act(el.dataset.action,true);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,()=>act(el.dataset.action,false));}function release(){for(const a in held)act(a,false);}window.addEventListener('blur',release);document.addEventListener('visibilitychange',release);window.addEventListener('pagehide',cleanup);
setInterval(()=>{if(phase==='running')for(const a in held)if(held[a])act(a,true);},180);setInterval(()=>{if(host&&state){state=tick(state,1/60);} },1000/60);setInterval(()=>{if(host&&state)publish();for(const [id,r]of connections)if(r.ready&&Date.now()-r.last>15000){if(host)remove(id);else stop('房主回應逾時，房間停止。');}},67);setInterval(()=>{for(const r of connections.values())if(r.ready)send(r.conn,{type:'ping'});},3000);
let pointer=null;
function intentAt(e){const b=canvas.getBoundingClientRect(),rx=Math.floor((e.clientX-b.left)/b.width*1200),ry=Math.floor((e.clientY-b.top)/b.height*440);return {type,x:type==='demolish'?rx:Math.floor(rx/40)*40,y:type==='demolish'?ry:Math.floor(ry/20)*20,...(['conveyor','fan'].includes(type)?{direction:$('direction').value}:{})};}
canvas.addEventListener('mousemove',e=>{pointer=intentAt(e);});canvas.addEventListener('mouseleave',()=>{pointer=null;canvas.dataset.preview='none';$('preview-status').textContent='滑鼠選機關，點賽道建造 · 每人一次';});
function box(c,x,y,w,h,fill,stroke='#29363d'){c.fillStyle=fill;c.fillRect(x,y,w,h);c.strokeStyle=stroke;c.lineWidth=2;c.strokeRect(x+1,y+1,w-2,h-2);}
function mechanism(c,o,time=0){const {x,y,w=40,h=20}=o,t=o.type,col=colors[Number(o.owner||1)-1];c.save();
if(t==='spike'){box(c,x,y+15,w,5,col);for(let i=0;i<2;i++){c.beginPath();c.moveTo(x+i*20,y+16);c.lineTo(x+i*20+10,y+1);c.lineTo(x+i*20+20,y+16);c.fillStyle='#edf1e6';c.fill();c.strokeStyle='#29363d';c.stroke();}}
else if(t==='spring'){box(c,x,y+15,w,5,col);c.strokeStyle='#29363d';c.lineWidth=3;c.beginPath();c.moveTo(x+8,y+15);for(let i=0;i<5;i++)c.lineTo(x+(i%2?30:10),y+14-i*2);c.stroke();box(c,x,y,w,5,col);}
else if(t==='saw'){for(const cx of [x+10,x+30]){c.save();c.translate(cx,y+10);c.rotate(time/160);c.beginPath();for(let i=0;i<32;i++){const a=i*Math.PI/16,r=i%2?7:10;c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fillStyle='#e3e8df';c.fill();c.strokeStyle='#29363d';c.stroke();c.fillStyle=col;c.beginPath();c.arc(0,0,3,0,7);c.fill();c.restore();}}
else if(t==='fan'){box(c,x,y,w,h,col);c.save();c.translate(x+20,y+10);c.rotate(time/130);c.fillStyle='#29363d';for(let i=0;i<4;i++){c.rotate(Math.PI/2);c.beginPath();c.ellipse(4,0,5,2,0,0,7);c.fill();}c.restore();c.fillStyle='#fff5df';c.font='bold 16px system-ui';c.fillText(({up:'↑',left:'←',right:'→'})[o.direction||'up'],x+29,y+16);}
else if(t==='demolish'){c.strokeStyle='#29363d';c.lineWidth=6;c.beginPath();c.moveTo(x+8,y+19);c.lineTo(x+28,y+2);c.stroke();box(c,x+23,y,16,8,'#e47760');}
else {box(c,x,y,w,h,t==='ice'?'#a5e2e9':col);if(t==='collapse'){c.strokeStyle='#29363d';c.beginPath();c.moveTo(x+25,y);c.lineTo(x+32,y+7);c.lineTo(x+21,y+12);c.lineTo(x+36,y+20);c.stroke();c.fillStyle='#29363d';c.font='bold 14px system-ui';c.fillText(o.collapseAt==null?'▱':'!',x+50,y+15);}else if(t==='ice'){c.fillStyle=col;c.fillRect(x+2,y+16,w-4,2);c.strokeStyle='#f4ffff';for(let i=10;i<w;i+=20){c.beginPath();c.moveTo(x+i,y+5);c.lineTo(x+i+9,y+15);c.stroke();}}else{c.fillStyle='#29363d';for(let i=6;i<w;i+=13){c.beginPath();c.arc(x+i,y+14,3,0,7);c.fill();}if(t==='conveyor'){c.fillStyle='#fff4d2';const shift=(time/80)%12;for(let k=0;k<w-12;k+=12)c.fillRect(x+k+shift,y+3,5,2);}c.font='bold 16px system-ui';c.fillText(t==='conveyor'?(o.direction==='left'?'⇐':'⇒'):'↔',x+w/2-8,y+13);}}
c.restore();}
for(const icon of document.querySelectorAll('[data-art]')){const c=icon.getContext('2d');mechanism(c,{type:icon.dataset.art,x:icon.dataset.art==='demolish'?20:0,y:10,w:['platform','conveyor','ice','collapse'].includes(icon.dataset.art)?80:40,h:20,owner:'1',direction:'right'});}
function background(now){ctx.fillStyle='#a8c3c2';ctx.fillRect(0,0,1200,440);ctx.fillStyle='#92b1b1';for(let x=20;x<1200;x+=200){box(ctx,x,85,125,140,'#bcd1c9','#7c9c9f');for(let i=0;i<3;i++){ctx.fillStyle='#91b2b6';ctx.fillRect(x+12+i*34,98,26,110);}}ctx.strokeStyle='#78989b';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(0,60);ctx.lineTo(1200,60);ctx.stroke();for(let x=240;x<1040;x+=160){ctx.strokeStyle='#56777e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,61);ctx.lineTo(x,190);ctx.stroke();box(ctx,x-14,184,28,12,'#f6c856');}ctx.fillStyle='#779998';ctx.fillRect(0,245,1200,135);for(let x=15;x<1200;x+=100){ctx.strokeStyle='#89a8a3';ctx.lineWidth=1;ctx.strokeRect(x,258,80,110);}ctx.fillStyle='#dce8cf';ctx.fillRect(0,300,180,80);ctx.fillStyle='#c2dfa4';ctx.fillRect(1080,270,120,110);ctx.fillStyle='#365950';ctx.font='bold 13px system-ui';ctx.fillText('出發碼頭',22,325);ctx.fillText('終點 +3',1100,292);ctx.strokeStyle='#3a594e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(1136,305);ctx.lineTo(1136,380);ctx.stroke();ctx.fillStyle='#e7f3cd';ctx.beginPath();ctx.moveTo(1138,306);ctx.lineTo(1175,317);ctx.lineTo(1138,331);ctx.fill();for(const pit of pits){ctx.fillStyle='#253a42';ctx.fillRect(pit.x,380,pit.w,60);ctx.fillStyle='#162b33';ctx.fillRect(pit.x+12,399,pit.w-24,41);}for(const b of bases){box(ctx,b.x,b.y,b.w,b.h,'#576e72');ctx.fillStyle='#f7ca59';ctx.fillRect(b.x,b.y,b.w,4);for(let x=b.x+8;x<b.x+b.w;x+=24){ctx.fillStyle='#243e45';ctx.fillRect(x,b.y+10,5,4);}if(b.h>20)for(let x=b.x;x<b.x+b.w;x+=24){ctx.fillStyle='#dba94c';ctx.beginPath();ctx.moveTo(x,b.y+6);ctx.lineTo(x+10,b.y+6);ctx.lineTo(x+20,b.y+18);ctx.lineTo(x+10,b.y+18);ctx.fill();}}}
function draw(now){background(now);if(phase==='build'){ctx.strokeStyle='#36535a25';ctx.lineWidth=1;for(let x=200;x<=1000;x+=40){ctx.beginPath();ctx.moveTo(x,200);ctx.lineTo(x,380);ctx.stroke();}for(let y=200;y<=380;y+=20){ctx.beginPath();ctx.moveTo(200,y);ctx.lineTo(1000,y);ctx.stroke();}}
for(const o of state?.obstacles??[]){if(o.type==='collapse'&&o.collapseAt!=null&&state.now>=o.collapseAt)continue;const x=phase==='build'?o.x:o.type==='platform'?platformX(o,state.now):o.type==='saw'?sawX(o,state.now):o.x;if(o.type==='fan'){const a=fanArea(o);ctx.fillStyle='#f4edbc35';ctx.fillRect(a.x,a.y,a.w,a.h);ctx.strokeStyle='#f4edbc';ctx.setLineDash([4,6]);ctx.strokeRect(a.x,a.y,a.w,a.h);ctx.setLineDash([]);ctx.fillStyle='#edf5d8';ctx.font='16px system-ui';for(let i=0;i<3;i++)ctx.fillText(({up:'↑',left:'←',right:'→'})[o.direction],a.x+10+i*20,a.y+25);}mechanism(ctx,{...o,x},matchMedia('(prefers-reduced-motion: reduce)').matches?0:now);}
if(!paintState||paintState.round!==state?.round||paintState.phase!==phase)paintState={round:state?.round,phase,players:{}};const alpha=1-Math.exp(-Math.min(100,now-lastFrame)/45);lastFrame=now;
for(const original of state?.players??[]){const q=paintState.players[original.id]??{x:original.x,y:original.y};q.x+=(original.x-q.x)*alpha;q.y+=(original.y-q.y)*alpha;paintState.players[original.id]=q;const p={...original,x:q.x,y:q.y},col=colors[Number(p.id)-1];ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=p.alive?1:.3;if(!p.alive){ctx.save();ctx.globalAlpha=.65;ctx.strokeStyle=col;ctx.lineWidth=2;for(let i=0;i<6;i++){const a=i*Math.PI/3,r=10+(now/70)%12;ctx.beginPath();ctx.moveTo(11+Math.cos(a)*r,15+Math.sin(a)*r);ctx.lineTo(11+Math.cos(a)*(r+4),15+Math.sin(a)*(r+4));ctx.stroke();}ctx.restore();}const step=Math.abs(p.vx)>10&&p.grounded?Math.sin(now/70)*2:0;box(ctx,1,12,20,14,col);box(ctx,2,3,18,13,col);ctx.fillStyle='#f5eedc';ctx.fillRect(4,7,14,6);ctx.fillStyle='#28383d';ctx.fillRect(p.vx<0?5:14,8,3,3);ctx.fillRect(2,26+step,7,4-step);ctx.fillRect(13,26-step,7,4+step);ctx.fillStyle='#eec05a';ctx.fillRect(0,3,22,3);if(p.id==='2'){ctx.fillStyle=col;ctx.fillRect(2,0,4,3);ctx.fillRect(16,0,4,3);ctx.fillStyle='#29363d';ctx.fillRect(7,17,8,2);}if(p.id==='3'){ctx.fillStyle='#29363d';ctx.fillRect(10,0,2,3);ctx.fillStyle=col;ctx.fillRect(7,0,8,2);ctx.fillStyle='#29363d';ctx.fillRect(4,7,14,3);}if(p.id==='4'){ctx.fillStyle='#e47760';ctx.fillRect(7,0,8,3);ctx.fillStyle='#29363d';ctx.fillRect(4,17,14,3);}ctx.fillStyle='#fff6d6';ctx.font='bold 10px system-ui';ctx.fillText(p.id,9,23);ctx.globalAlpha=1;if(p.id===self){ctx.fillStyle='#29363d';ctx.fillRect(-7,-19,36,14);ctx.fillStyle=col;ctx.font='bold 10px system-ui';ctx.fillText('你 P'+p.id,-4,-9);ctx.beginPath();ctx.moveTo(8,-4);ctx.lineTo(14,-4);ctx.lineTo(11,0);ctx.fill();}ctx.restore();}
if(pointer&&phase==='build'){const m={...pointer,type,...(['fan','conveyor'].includes(type)?{direction:$('direction').value}:{})};if(!['fan','conveyor'].includes(type))delete m.direction;const legal=place(state,self,m)!==state,target=type==='demolish'?state?.obstacles.find(o=>m.x>=o.x&&m.x<o.x+o.w&&m.y>=o.y&&m.y<o.y+o.h):null,o=target??{...m,w:['platform','conveyor','ice','collapse'].includes(type)?80:40,h:20,owner:self};canvas.dataset.preview=legal?'valid':'invalid';canvas.dataset.previewType=type;canvas.dataset.previewX=o.x;canvas.dataset.previewY=o.y;ctx.globalAlpha=.55;if(type!=='demolish')mechanism(ctx,o,now);ctx.globalAlpha=1;ctx.strokeStyle=legal?'#2b9b54':'#ce493e';ctx.lineWidth=3;ctx.setLineDash([5,3]);ctx.strokeRect(o.x-2,o.y-2,o.w+4,o.h+4);ctx.setLineDash([]);$('preview-status').textContent=legal?(type==='demolish'?'可拆除 · 點擊拆除這件機關':'可建造 · 點擊放置'):'不可操作 · 避開安全區、重疊與固定地形';}requestAnimationFrame(draw);}requestAnimationFrame(draw);
const room=new URLSearchParams(location.hash.slice(1)).get('room');if(room!==null){if(/^ow-[0-9a-f]{32}$/.test(room))start(room);else stop('邀請連結無效');}else render();
